apiVersion: v1
kind: Secret
metadata:
  name: cred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ2YWxheHkyMjcuamZyb2cuaW8iOiB7CgkJCSJhdXRoIjogIllXMXBjbTFoYmpwQmJXbHlRRGd4TWpFPSIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson